using Caminhoneiro.DTO;
using System.Collections.Generic;

namespace Caminhoneiro.Entidade
{
	public class Seguradoras
    {
		public Seguradoras()
		{
			GetSeguradoras();
		}
		internal static List<TabelaApoioDTO> _Itens = null;
		public static List<TabelaApoioDTO> Itens() { return _Itens; }
		internal void GetSeguradoras()
        {
			_Itens = new List<TabelaApoioDTO>() {
				new TabelaApoioDTO  { Id = 1, Codigo = "3314", Texto = "Etiam Ligula LLP" },
				new TabelaApoioDTO  { Id = 2, Codigo = "4408", Texto = "Luctus Felis Industries" },
				new TabelaApoioDTO  { Id = 3, Codigo = "1090", Texto = "Nam Incorporated" },
				new TabelaApoioDTO  { Id = 4, Codigo = "1911", Texto = "Nulla Eget Metus Foundation" },
				new TabelaApoioDTO  { Id = 5, Codigo = "4150", Texto = "Eget Consulting" },
				new TabelaApoioDTO  { Id = 6, Codigo = "1260", Texto = "Laoreet Libero Et Institute" },
				new TabelaApoioDTO  { Id = 7, Codigo = "1900", Texto = "Cras Inc." },
				new TabelaApoioDTO  { Id = 8, Codigo = "3074", Texto = "Urna Industries" },
				new TabelaApoioDTO  { Id = 9, Codigo = "2991", Texto = "Ac Institute" },
				new TabelaApoioDTO  { Id = 10, Codigo = "746", Texto = "Mattis Corp." },
				new TabelaApoioDTO  { Id = 11, Codigo = "1340", Texto = "Duis Gravida Inc." },
				new TabelaApoioDTO  { Id = 12, Codigo = "4935", Texto = "Suspendisse Consulting" },
				new TabelaApoioDTO  { Id = 13, Codigo = "1032", Texto = "Praesent Luctus Curabitur Institute" },
				new TabelaApoioDTO  { Id = 14, Codigo = "4970", Texto = "Lorem Lorem Ltd" },
				new TabelaApoioDTO  { Id = 15, Codigo = "4872", Texto = "Pede Praesent Eu Limited" },
				new TabelaApoioDTO  { Id = 16, Codigo = "2084", Texto = "Proin Nisl Corporation" },
				new TabelaApoioDTO  { Id = 17, Codigo = "4964", Texto = "Ligula Nullam Foundation" },
				new TabelaApoioDTO  { Id = 18, Codigo = "2772", Texto = "Sem PC" },
				new TabelaApoioDTO  { Id = 19, Codigo = "1068", Texto = "Placerat Eget Venenatis Corporation" },
				new TabelaApoioDTO  { Id = 20, Codigo = "4980", Texto = "Ultricies Institute" },
				new TabelaApoioDTO  { Id = 21, Codigo = "1353", Texto = "Donec Tempus PC" },
				new TabelaApoioDTO  { Id = 22, Codigo = "2810", Texto = "Sed Nec Metus Corporation" },
				new TabelaApoioDTO  { Id = 23, Codigo = "4756", Texto = "Imperdiet LLC" },
				new TabelaApoioDTO  { Id = 24, Codigo = "2501", Texto = "Mauris Non Dui LLP" },
				new TabelaApoioDTO  { Id = 25, Codigo = "3559", Texto = "Aliquam PC" },
				new TabelaApoioDTO  { Id = 26, Codigo = "1289", Texto = "Montes Nascetur Industries" },
				new TabelaApoioDTO  { Id = 27, Codigo = "2426", Texto = "Porttitor Tellus Non Ltd" },
				new TabelaApoioDTO  { Id = 28, Codigo = "3579", Texto = "Etiam Laoreet PC" },
				new TabelaApoioDTO  { Id = 29, Codigo = "4234", Texto = "Aenean Industries" },
				new TabelaApoioDTO  { Id = 30, Codigo = "3079", Texto = "Luctus Curabitur Foundation" },
				new TabelaApoioDTO  { Id = 31, Codigo = "3545", Texto = "Imperdiet Ornare In Corporation" },
				new TabelaApoioDTO  { Id = 32, Codigo = "2870", Texto = "Sed Auctor Company" },
				new TabelaApoioDTO  { Id = 33, Codigo = "3134", Texto = "Sapien Nunc Pulvinar Company" },
				new TabelaApoioDTO  { Id = 34, Codigo = "1063", Texto = "Quisque LLC" },
				new TabelaApoioDTO  { Id = 35, Codigo = "2347", Texto = "Vitae Aliquet Nec Consulting" },
				new TabelaApoioDTO  { Id = 36, Codigo = "1458", Texto = "Non Enim Commodo Corp." },
				new TabelaApoioDTO  { Id = 37, Codigo = "1584", Texto = "Rhoncus Donec Est LLP" },
				new TabelaApoioDTO  { Id = 38, Codigo = "4365", Texto = "Lorem Incorporated" },
				new TabelaApoioDTO  { Id = 39, Codigo = "4362", Texto = "Arcu Vestibulum Ante Limited" },
				new TabelaApoioDTO  { Id = 40, Codigo = "3922", Texto = "Eget Massa LLC" },
				new TabelaApoioDTO  { Id = 41, Codigo = "3965", Texto = "Donec Felis Industries" },
				new TabelaApoioDTO  { Id = 42, Codigo = "3844", Texto = "Eu Neque Limited" },
				new TabelaApoioDTO  { Id = 43, Codigo = "4204", Texto = "Suspendisse Commodo Tincidunt Company" },
				new TabelaApoioDTO  { Id = 44, Codigo = "3513", Texto = "Suscipit LLC" },
				new TabelaApoioDTO  { Id = 45, Codigo = "3315", Texto = "Fusce Company" },
				new TabelaApoioDTO  { Id = 46, Codigo = "2675", Texto = "Enim Commodo Inc." },
				new TabelaApoioDTO  { Id = 47, Codigo = "4911", Texto = "Et Magnis Dis LLC" },
				new TabelaApoioDTO  { Id = 48, Codigo = "3778", Texto = "Phasellus Fermentum Convallis LLC" },
				new TabelaApoioDTO  { Id = 49, Codigo = "3067", Texto = "Facilisis Facilisis Magna Inc." },
				new TabelaApoioDTO  { Id = 50, Codigo = "4687", Texto = "Et Magnis Dis Ltd" },
				new TabelaApoioDTO  { Id = 51, Codigo = "4172", Texto = "Phasellus Vitae Mauris Company" },
				new TabelaApoioDTO  { Id = 52, Codigo = "3078", Texto = "Vitae Dolor Corp." },
				new TabelaApoioDTO  { Id = 53, Codigo = "1937", Texto = "Donec Institute" },
				new TabelaApoioDTO  { Id = 54, Codigo = "3227", Texto = "Eu Odio Industries" },
				new TabelaApoioDTO  { Id = 55, Codigo = "3958", Texto = "Nunc LLP" },
				new TabelaApoioDTO  { Id = 56, Codigo = "659", Texto = "Semper Nam Tempor Foundation" },
				new TabelaApoioDTO  { Id = 57, Codigo = "1892", Texto = "Pellentesque Eget Dictum Ltd" },
				new TabelaApoioDTO  { Id = 58, Codigo = "2048", Texto = "Id Blandit At Inc." },
				new TabelaApoioDTO  { Id = 59, Codigo = "1181", Texto = "Orci Quis Lectus Foundation" },
				new TabelaApoioDTO  { Id = 60, Codigo = "3915", Texto = "Quis Massa Inc." },
				new TabelaApoioDTO  { Id = 61, Codigo = "3162", Texto = "Natoque Penatibus Et Limited" },
				new TabelaApoioDTO  { Id = 62, Codigo = "1522", Texto = "Auctor Nunc Nulla Ltd" },
				new TabelaApoioDTO  { Id = 63, Codigo = "4031", Texto = "Nibh Lacinia Corp." },
				new TabelaApoioDTO  { Id = 64, Codigo = "3108", Texto = "Pharetra Quisque Inc." },
				new TabelaApoioDTO  { Id = 65, Codigo = "2478", Texto = "Enim Etiam Gravida Ltd" },
				new TabelaApoioDTO  { Id = 66, Codigo = "4004", Texto = "Nulla Tincidunt Institute" },
				new TabelaApoioDTO  { Id = 67, Codigo = "1848", Texto = "Tempus Lorem Fringilla LLC" },
				new TabelaApoioDTO  { Id = 68, Codigo = "2269", Texto = "Mus Proin Corp." },
				new TabelaApoioDTO  { Id = 69, Codigo = "1077", Texto = "Ut Odio Vel Consulting" },
				new TabelaApoioDTO  { Id = 70, Codigo = "867", Texto = "Molestie Industries" },
				new TabelaApoioDTO  { Id = 71, Codigo = "2712", Texto = "Arcu Morbi Ltd" },
				new TabelaApoioDTO  { Id = 72, Codigo = "3246", Texto = "Magna Et Incorporated" },
				new TabelaApoioDTO  { Id = 73, Codigo = "1370", Texto = "Cras Eu Tellus Incorporated" },
				new TabelaApoioDTO  { Id = 74, Codigo = "4645", Texto = "Fermentum LLC" },
				new TabelaApoioDTO  { Id = 75, Codigo = "2427", Texto = "Aliquam Incorporated" },
				new TabelaApoioDTO  { Id = 76, Codigo = "1935", Texto = "At LLC" },
				new TabelaApoioDTO  { Id = 77, Codigo = "842", Texto = "In Institute" },
				new TabelaApoioDTO  { Id = 78, Codigo = "1707", Texto = "Parturient Montes Limited" },
				new TabelaApoioDTO  { Id = 79, Codigo = "1249", Texto = "Sed Sem Egestas LLP" },
				new TabelaApoioDTO  { Id = 80, Codigo = "4015", Texto = "Cursus Et Incorporated" },
				new TabelaApoioDTO  { Id = 81, Codigo = "4357", Texto = "Eu Odio Incorporated" },
				new TabelaApoioDTO  { Id = 82, Codigo = "3506", Texto = "Purus Maecenas Libero LLC" },
				new TabelaApoioDTO  { Id = 83, Codigo = "1447", Texto = "Non Corporation" },
				new TabelaApoioDTO  { Id = 84, Codigo = "1117", Texto = "Convallis Inc." },
				new TabelaApoioDTO  { Id = 85, Codigo = "2075", Texto = "Ut Limited" },
				new TabelaApoioDTO  { Id = 86, Codigo = "1878", Texto = "Aliquam Rutrum Industries" },
				new TabelaApoioDTO  { Id = 87, Codigo = "1061", Texto = "Pellentesque Tellus LLC" },
				new TabelaApoioDTO  { Id = 88, Codigo = "2902", Texto = "Lobortis Risus LLC" },
				new TabelaApoioDTO  { Id = 89, Codigo = "1809", Texto = "Tempor Diam Limited" },
				new TabelaApoioDTO  { Id = 90, Codigo = "4459", Texto = "Eget Associates" },
				new TabelaApoioDTO  { Id = 91, Codigo = "3183", Texto = "Non Hendrerit Company" },
				new TabelaApoioDTO  { Id = 92, Codigo = "1340", Texto = "Sem Egestas Limited" },
				new TabelaApoioDTO  { Id = 93, Codigo = "4595", Texto = "Ut Molestie In Industries" },
				new TabelaApoioDTO  { Id = 94, Codigo = "1043", Texto = "Non Ante Institute" },
				new TabelaApoioDTO  { Id = 95, Codigo = "4745", Texto = "Etiam Imperdiet Corp." },
				new TabelaApoioDTO  { Id = 96, Codigo = "3338", Texto = "Pellentesque Eget Industries" },
				new TabelaApoioDTO  { Id = 97, Codigo = "808", Texto = "Mi Lacinia Mattis Institute" },
				new TabelaApoioDTO  { Id = 98, Codigo = "1417", Texto = "In Hendrerit Limited" },
				new TabelaApoioDTO  { Id = 99, Codigo = "3485", Texto = "Pellentesque Massa Incorporated" },
				new TabelaApoioDTO  { Id = 100, Codigo = "3967", Texto = "Senectus Et Netus Company" }
			};

		}
	}
}
